#! /bin/sh
folder="`dirname $0`"
# check the param
while getopts u:l:m:b: name
do
 case $name in
  u) url=$OPTARG;;
  l) layer=$OPTARG;;
  m) mode=$OPTARG;;
  b) bbox=$OPTARG;;
esac
done



if [ -z "$url" ]
then
	echo "Error ! Missing Parameters" >&2
	echo "" >&2
	echo "Usage: owc-wms -u <getCapabilities url> [-l <entry name>] [-b <minx,miny,maxx,maxx>] [-m <mode>]" >&2
	echo "Transform OGC Services (WMS 1.1.1/1.3.0, WFS 1.1.0) GetCapabilities documents in OGC Context Document in ATOM encoding version 1.0." >&2
        echo "It maps the service to a feed and assumes all named layers are entries" >&2
        echo "-u : The url or relative location of the OGC GetCabilities URL (Mandatory) " >&2
        echo "-l : The entry name to be processed. This will produce only one entry (Optional)" >&2
        echo "-b : The bounding box to restrict the requests. This parameter will override the layers bounding boxes (Optional)" >&2
        echo "-m : The processing mode (Optional) " >&2
       	echo "		if equal to 'feed' it will produce a valid ATOM feed (default)." >&2
       	echo "		If equal to 'fragment' it will only produce the entry of a layer. It must be used with the entry parameter." >&2
       	echo "		If equal to 'fragment-url' it will only produce the entry URLS with the feature or layer request. It must be used with the entry parameter." >&2
       	echo "		If equal to 'list' it will show all the entries available on the OGC GetCapabilities documents." >&2
       	echo " "
	exit -1
fi



echo $url >&2

curl "$url" | xsltproc --novalid --stringparam bbox "$bbox" --stringparam entry "$layer" --stringparam mode "$mode" --stringparam now "`date +%Y-%m-%dT%H:%M:%S`" $folder/../xslt/ows2owc.xsl - 
